### ISSUE TITLE
[Request] Select monitor in multi-monitor setup

### ISSUE THREAD

**Issue by Exynom** [bp2008/BetterClearTypeTuner#11]
In the ClearType dialog one can pick which monitor to apply the changes to, in your application that is not possible so far. Would it be hard to add it or is this already implemented in a mechanic I didn't find?

Best regards,
Andreas

**Comment by bp2008** [comment]
No, there is even a note about that in the sidebar of the app.  If I recall, the ability to choose a monitor in the official cleartype tuner doesn't actually do anything.  I'd love to be proven wrong, but I don't think Microsoft actually implemented per-monitor text rendering settings.

**Comment by bp2008** [comment]
I also found a note I wrote about that, [at the bottom of this page in the wiki](https://github.com/bp2008/BetterClearTypeTuner/wiki/ClearType-Investigations).

> As far as I know, the monitor-specific nature of these registry keys never mattered, and everything always just used the settings of the primary display. It is possible that some applications read from these older locations to determine font rendering settings.

**Comment by mdrejhon** [comment]
Hola @bp2008 

I am corresponding with Microsoft about a theoretical "ClearType 2", which I mention about this;
https://github.com/microsoft/PowerToys/issues/25595

Just wanted to reach you out, to raise your awareness.  Although needing incubation (to support the odd OLED pixel structures), a simple font library using the simple algorithm for applications (for now), or maybe we can collaborate on that together, as some early incubation path.  Thoughts are welcome.

**Comment by bp2008** [comment]
Hi @mdrejhon.  Thank you for your efforts to get things changed.  Solving this is certainly very challenging, both on a technical level and a "human" level.

Most people:
1. Struggle to see the issue (literally) even if you show them what to look for.
2. Don't understand the issue.
3. Don't care about the issue.
4. All of the above.

Therefore even with an ideal outcome where all of your recommendations were followed and we got optimal subpixel antialiasing for all displays, I have to wonder how much value it would really add for users.  Ideally, it could improve text legibility on a lot of displays.  But if 95% of users can't tell the difference, is it truly worth doing?  It almost seems as though everyone is just waiting for higher DPI displays to make subpixel antialiasing entirely obsolete.

I have the 42" C2 OLED as a primary display at 100% scale, so I like the sample you put together demonstrating that even a slightly simplified "RBG" antialiasing method looks better than other methods on an RWBG OLED panel.

I would be thrilled if they only went as far as to implement that as a third subpixel antialiasing option.  I suspect there would be some edge cases where visual artifacts still appear, which a much more advanced antialiasing method might be able to mitigate.  e.g. yellow text on white background with no antialiasing shows red fringes on the left, and light green fringes on the right, due to there being a white and a black (blue, but off) subpixel between the red and green subpixels.

![YellowOnWhite](https://user-images.githubusercontent.com/5639911/233454900-78d9f94c-25b8-4e7b-bc14-b378745b2245.png)

![YellowOnWhite_OLED_ZOOM2](https://user-images.githubusercontent.com/5639911/233457895-8b7da5fc-df08-44d6-b0cd-0438e461c1e9.jpg)

I do think a simple font rendering library could be useful as a proof of concept, and as a test bed for developing subpixel antialiasing methodology, but I am not particularly motivated to spend a lot of time working on it.

**Comment by bp2008** [comment]
I should also note the green text in your image says "R-W-G-B" when "R-W-B-G" was intended.

**Comment by mdrejhon** [comment]
Yes, I have commented very heavily in the [H]ardForum thread.

The other thing is that this can be tweaked at the manufacturer level to create a BGRW mode out of half-pixel-shifting an RWBG panel.  Since [RWBG][RWBG][RWBG][RWBG] can become RW][BGRW][BGRW][BGRW][RW and fix both the yellow fringing and the ClearType compatibility issue, by making BGR contiguous and keeping the brightest pixel groups contiguous (G+R+W).  This does increase blue fringing a smidge but that's far more minor and unnoticeable than yellow fringing.   

As founder of Blur Busters / TestUFO, I am currently in the fortunate situation of being in a contract with LG Korea, I'm working the problem at both ends concurrently.  See if LG fixes it first, or Microsoft fixes it first, or somehow meets in the middle creatively.  Microsoft creating a ClearType 2 would be more universal (not WOLED specific), but the LG-side fix would also fix the yellow fringing for mudane gaming cases too.

**Comment by bp2008** [comment]
Great job with Blur Busters.  I thought your name was familiar but I totally glossed over the avatar of the Test UFO!

Just a thought.  A proof-of-concept text rendering library with better subpixel antialiasing capability should probably be built in JavaScript to target the HTML5 canvas, and that way it is relatively easily accessible for demonstration purposes with high DPI support in a cross-platform manner.

**Comment by mdrejhon** [comment]
> I should also note the green text in your image says "R-W-G-B" when "R-W-B-G" was intended.

Thank you for pointing out my typo.  Here's the new one.  I'm replacing all my public posts with this one.

![image](https://user-images.githubusercontent.com/59981975/233461657-a5883b2a-c9ae-479a-943f-b33eba90555d.png)

Even if you're not going to commit much time, I'd like you to monitor https://github.com/microsoft/PowerToys/issues/25595 and upvote anything you like.  At least it will help raise awareness.  Somebody already commented in there, that I should be working for Microsoft.

**Comment by mdrejhon** [comment]
> Just a thought. A proof-of-concept text rendering library with better subpixel antialiasing capability should probably be built in JavaScript to target the HTML5 canvas, and that way it is relatively easily accessible for demonstration purposes with high DPI support in a cross-platform manner.

In fact... I am considering implementing the posted algorithm as a TestUFO font renderer, as a proof of concept!  

I already have a custom script that essentially detect incorrectness of **product(OS DPI zoom %, browser zoom %)** that works in all desktop and mobile browsers, so I can prompt a message "Not Native Resolution".

**Comment by bp2008** [comment]
@mdrejhon I noticed today that MacType preview builds have support for custom subpixel structures, so I did a little experimenting and I think you will be interested: https://github.com/snowie2000/mactype/issues/720#issuecomment-1517033758
