### ISSUE TITLE
Toggle Dark/Light mode 

### ISSUE THREAD

**Issue by thebigsmileXD** [bp2008/BetterClearTypeTuner#8]
As the title states, a button to change the color to dark mode would be great since M$ explorer can now be dark

**Comment by thany** [comment]
Or pick up this setting automatically.

**Comment by thebigsmileXD** [comment]
That's true as well
My idea was initially just so you can see if it renders fine in both modes

**Comment by bp2008** [comment]
This app is not built on a particularly modern UI framework, so dark mode is not natively supported.  But I was able to add a dark mode manually in [version 1.4](https://github.com/bp2008/BetterClearTypeTuner/releases/tag/1.4).  It should be automatically detected if you have Windows set to use dark mode in apps, but otherwise you'll need to click the checkbox at the top of the app.
